name: Build & Deploy dashboard-backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Docker image
        run: docker build --pull -t dashboard-backend:latest .

      - name: Save Docker image as tar
        run: docker save dashboard-backend:latest -o dashboard-backend.tar

      - name: Fix permissions for Docker image tar
        run: chmod 644 dashboard-backend.tar

      - name: Copy Docker image tar to server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dashboard-backend.tar"
          target: "/root/dashboard-backend.tar"

      - name: SSH and deploy Docker container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ls -lah /root/dashboard-backend.tar
            docker stop dashboard-backend || true
            docker rm dashboard-backend || true
            docker rmi dashboard-backend:latest || true
            docker load -i /root/dashboard-backend.tar
            docker run -d --restart unless-stopped --name dashboard-backend -p 8081:8080 dashboard-backend:latest